
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20140808 (SVN rev 54)
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int LLADER = 4;
  public static final int EVE = 7;
  public static final int COMA = 5;
  public static final int FYH = 11;
  public static final int TIP = 6;
  public static final int EOF = 0;
  public static final int PYC = 9;
  public static final int SEPARADOR = 10;
  public static final int ESP = 2;
  public static final int error = 1;
  public static final int LLAIZQ = 3;
  public static final int CAD = 8;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "ESP",
  "LLAIZQ",
  "LLADER",
  "COMA",
  "TIP",
  "EVE",
  "CAD",
  "PYC",
  "SEPARADOR",
  "FYH"
  };
}

