
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Mon Jan 12 17:28:08 CET 2015
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int LLADER = 3;
  public static final int EVE = 9;
  public static final int COMA = 4;
  public static final int FYH = 11;
  public static final int TIP = 8;
  public static final int EOF = 0;
  public static final int PYC = 5;
  public static final int SEPARADOR = 6;
  public static final int ESP = 7;
  public static final int error = 1;
  public static final int LLAIZQ = 2;
  public static final int CAD = 10;
}

