
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20140808 (SVN rev 54)
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int NUM = 2;
  public static final int MENOS = 4;
  public static final int EOF = 0;
  public static final int PYC = 5;
  public static final int MAS = 3;
  public static final int PARIZQ = 6;
  public static final int DIV = 8;
  public static final int error = 1;
  public static final int PARDER = 7;
  public static final int MUL = 9;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "NUM",
  "MAS",
  "MENOS",
  "PYC",
  "PARIZQ",
  "PARDER",
  "DIV",
  "MUL"
  };
}

